//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/ActionMaps/InputControllerMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControllerMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControllerMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControllerMap"",
    ""maps"": [
        {
            ""name"": ""Scene Controller"",
            ""id"": ""7ae2c900-872f-4272-aa86-34d4805e7fcb"",
            ""actions"": [
                {
                    ""name"": ""Spawn AI"",
                    ""type"": ""Button"",
                    ""id"": ""331d58e0-ea0a-420b-a079-2f16028758e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2be164ba-d29d-4632-8f3c-b4dd5e9c9fdf"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn AI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Scene Controller
        m_SceneController = asset.FindActionMap("Scene Controller", throwIfNotFound: true);
        m_SceneController_SpawnAI = m_SceneController.FindAction("Spawn AI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Scene Controller
    private readonly InputActionMap m_SceneController;
    private List<ISceneControllerActions> m_SceneControllerActionsCallbackInterfaces = new List<ISceneControllerActions>();
    private readonly InputAction m_SceneController_SpawnAI;
    public struct SceneControllerActions
    {
        private @InputControllerMap m_Wrapper;
        public SceneControllerActions(@InputControllerMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @SpawnAI => m_Wrapper.m_SceneController_SpawnAI;
        public InputActionMap Get() { return m_Wrapper.m_SceneController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SceneControllerActions set) { return set.Get(); }
        public void AddCallbacks(ISceneControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_SceneControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SceneControllerActionsCallbackInterfaces.Add(instance);
            @SpawnAI.started += instance.OnSpawnAI;
            @SpawnAI.performed += instance.OnSpawnAI;
            @SpawnAI.canceled += instance.OnSpawnAI;
        }

        private void UnregisterCallbacks(ISceneControllerActions instance)
        {
            @SpawnAI.started -= instance.OnSpawnAI;
            @SpawnAI.performed -= instance.OnSpawnAI;
            @SpawnAI.canceled -= instance.OnSpawnAI;
        }

        public void RemoveCallbacks(ISceneControllerActions instance)
        {
            if (m_Wrapper.m_SceneControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISceneControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_SceneControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SceneControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SceneControllerActions @SceneController => new SceneControllerActions(this);
    public interface ISceneControllerActions
    {
        void OnSpawnAI(InputAction.CallbackContext context);
    }
}
